version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DJANGO_SETTINGS_MODULE=myproject.settings
      - DB_ENGINE=mysql
      - DB_NAME=storefront
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=new_password
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=storefront
      - MYSQL_ROOT_PASSWORD=new_password
